server:
  port: 8090

spring:
  application:
    name: notification-service

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# base URL for user-service (used by UserClient)
user-service:
  base-url: http://localhost:8084

# FCM server key for legacy API method (dev).
# For production use FCM v1 with Google OAuth2/service account token.
fcm:
  server-key: "AAAA...YOUR_FCM_SERVER_KEY_HERE..."
